import type { Artifact } from "../schemas";

/**
 * Pure string templates for the files `deployoor generate` emits. Kept pure so they
 * can be snapshot- and tsc-checked in isolation. Two modules per contract:
 *   types/<Name>.ts   — the typed artifact (abi as const), type-only `deployoor` import
 *   <Name>.ts         — the deployer: `getOrDeploy<Name> = defineDeployer(artifact, config)`
 * plus an index barrel of explicit named exports (never `export *`).
 */

const lowerFirst = (s: string): string => (s.length === 0 ? s : `${s[0]?.toLowerCase() ?? ""}${s.slice(1)}`);
const artifactConstName = (name: string): string => `${lowerFirst(name)}Artifact`;

const AUTOGEN = "// AUTO-GENERATED by deployoor. Do not edit by hand.";

export const artifactModule = (artifact: Artifact, packageName: string): string => `${AUTOGEN}
import type { TypedArtifact } from "${packageName}";

const abi = ${JSON.stringify(artifact.abi)} as const;

export const ${artifactConstName(artifact.name)} = {
  name: ${JSON.stringify(artifact.name)},
  abi,
  bytecode: ${JSON.stringify(artifact.bytecode)},
  metadata: ${JSON.stringify(artifact.metadata)},
} satisfies TypedArtifact<typeof abi>;
`;

export const deployerModule = (
  artifact: Artifact,
  opts: { packageName: string; configImport: string },
): string => `${AUTOGEN}
import { defineDeployer } from "${opts.packageName}";
import config from "${opts.configImport}";
import { ${artifactConstName(artifact.name)} } from "./types/${artifact.name}";

export const getOrDeploy${artifact.name} = defineDeployer(${artifactConstName(artifact.name)}, config);
`;

export const indexModule = (names: ReadonlyArray<string>): string =>
  `${AUTOGEN}\n${names.map((n) => `export { getOrDeploy${n} } from "./${n}";`).join("\n")}\n`;
