import { describe, it, expect } from "vitest";
import { createTestClients } from "@deployoor/testing";
// Generated by `deployoor generate` from the Foundry `out/` artifacts (see the `e2e` script).
import { getOrDeployCounter } from "../deployers";

describe("foundry example", () => {
  it("deploys the Foundry-compiled Counter to an in-memory EVM — no node, no disk", async () => {
    // Spreading `clients` passes the in-memory store, so nothing is written to deployments/.
    const clients = await createTestClients();

    const counter = await getOrDeployCounter({ ...clients, args: [7n] });
    expect(counter.address).toMatch(/^0x[0-9a-fA-F]{40}$/);

    // typed viem object straight from the generated deployer
    expect(await counter.read.number()).toBe(7n);
    await counter.write.increment();
    expect(await counter.read.number()).toBe(8n);
  });
});
