import { describe, it, expect, beforeEach } from "vitest";
import { rmSync } from "node:fs";
import { join } from "node:path";
import { createTestClients } from "@deployoor/testing";
// Generated by `deployoor generate` from the Foundry `out/` artifacts (see the `e2e` script).
import { getOrDeployCounter } from "../deployers";

describe("foundry example", () => {
  // Each tevm run is a fresh chain, but deployoor persists the deployment record to
  // deployments/. Clear it so the test always deploys fresh instead of reusing a
  // recorded address that doesn't exist on the new in-memory EVM.
  beforeEach(() => rmSync(join(import.meta.dirname, "..", "deployments"), { recursive: true, force: true }));

  it("deploys the Foundry-compiled Counter to an in-memory EVM — no node", async () => {
    const { walletClient, publicClient } = await createTestClients();

    const counter = await getOrDeployCounter({ walletClient, publicClient, args: [7n] });
    expect(counter.address).toMatch(/^0x[0-9a-fA-F]{40}$/);

    // typed viem object straight from the generated deployer
    expect(await counter.read.number()).toBe(7n);
    await counter.write.increment();
    expect(await counter.read.number()).toBe(8n);
  });
});
