import { describe, it, expect, beforeEach } from "vitest";
import { rmSync } from "node:fs";
import { join } from "node:path";
import { createTestClients } from "@deployoor/testing";
// Generated by `deployoor generate` from the Hardhat `artifacts/` (see the `e2e` script).
import { getOrDeployCounter } from "../deployers";

describe("hardhat example", () => {
  // Fresh tevm chain each run, but deployoor persists the deployment record — clear it
  // so we deploy fresh instead of reusing an address that isn't on the new EVM.
  beforeEach(() => rmSync(join(import.meta.dirname, "..", "deployments"), { recursive: true, force: true }));

  it("deploys the Hardhat-compiled Counter to an in-memory EVM — no node", async () => {
    const { walletClient, publicClient } = await createTestClients();

    const counter = await getOrDeployCounter({ walletClient, publicClient, args: [7n] });
    expect(counter.address).toMatch(/^0x[0-9a-fA-F]{40}$/);

    expect(await counter.read.number()).toBe(7n);
    await counter.write.increment();
    expect(await counter.read.number()).toBe(8n);
  });
});
